# ChatSync - Конфигурация
# Синхронизатор чата Minecraft и Telegram
# Авторы: gordey9992 & DeepSeek

# Настройки Telegram
telegram:
  enabled: true
  bot-token: "8263486505:AAHs0FDTQJrNRoMd1loLaNASWrp4SfKEuRc"
  chat-id: "-1002935953089"
  thread-id: 434
  broadcast-events: true

# Настройки синхронизации чата
chat-sync:
  # Включить/выключить синхронизацию чата
  enabled: true
  
  # Минимальная длина сообщения для отправки в Telegram
  min-message-length: 2
  
  # Список запрещенных слов (сообщения с этими словами не будут отправляться)
  banned-words:
    - "оскорбление"
    - "мат"
    - "спам"
  
  # События для синхронизации
  events:
    player-join: true
    player-leave: true
    player-death: true
    player-achievement: true
    server-commands: true
  
  # Форматы сообщений (можно изменить в messages.yml)
  formats:
    chat-to-telegram: "🎮 **%s%s**: %s"
    player-join: "🟢 **%s** присоединился к серверу"
    player-leave: "🔴 **%s** покинул сервер"
    player-death: "💀 %s"
    server-message: "⚡ **Сервер**: %s"

# Настройки логгирования
logging:
  # Логировать сообщения в консоль сервера
  log-to-console: true
  
  # Логировать входящие сообщения из Telegram
  log-telegram-messages: true
  
  # Уровень детализации логов (INFO, WARNING, SEVERE)
  log-level: "INFO"
